### ISSUE TITLE
[Suggestion] Compatibility with ValleyCraft & BetterNether/End chains

### ISSUE THREAD

**Issue by ayukays** [legoatoom/ConnectibleChains#13]
[ValleyCraft](https://modrinth.com/mod/valleycraft), [BetterNether](https://www.curseforge.com/minecraft/mc-mods/betternether) & [BetterEnd](https://www.curseforge.com/minecraft/mc-mods/betterend)  have different types of chains like gold, copper, netherite and etc. Would be nice to have compatibility :)

![image](https://user-images.githubusercontent.com/81534459/149674162-7ebb7c1f-e92c-4a07-85f0-b4efecc59678.png)

**Comment by Qendolin** [comment]
I've stared working on this feature and am progressing quite well, one thing that is holding me back however is how the mod keeps track of links. You have a source knot that knows that is connected to a destination knot and that's basically it. The source knot keeps track of all the information, that's why in creative mode items still drop when breaking one of the knots (the dst knot). So with the current system this would not be possible:
`fence --- copper_chain --- fence --- gold_chain --- fence` because there's 1 knot per fence and 1 type per knot. A class like `ChainLink` with `KnotA, KnotB, Type` would be useful. Any comments @legoatoom?

**Comment by legoatoom** [comment]
You firstly have to ask yourself does it matter if a source chain connects to a chainlink that is from a different type?
Can only gold chains connect to gold chains or can they all interlock, if that is the case it doesn't matter about the how it is defined, the source just needs to keep track of the types then aswell.

**Comment by efffauw** [comment]
Also compatibility with [Mythic Metals Decorations](https://www.curseforge.com/minecraft/mc-mods/mythicmetals-decorations)

**Comment by Qendolin** [comment]
I wouldn't mind refactoring the linking, IMO the ChainKnotEntity class is too big and a little messy anyway. If you don't mind I'm gonna refactor the linking system and make it simpler / less prone to edge cases like #14.

**Comment by legoatoom** [comment]
I rather you not change too much from the ChainKnotEntity. I mimicked most of the code from Mojang and the connections are working fine and pretty smoothly. You risk creating more bugs.

**Comment by Qendolin** [comment]
There is a joke about mojank code in this somewhere 😆

**Comment by Qendolin** [comment]
@efffauw That would be too much work for me. Once the next update is out you should open an issue in their repo to add compatibility. A guide for mod authors will also be released with the update.

**Comment by Qendolin** [comment]
Please also note that ConnectibleChains will not be maintaining the compatibility for ValleyCraft & BetterNether/End. If it breaks in the future create an issue in their repos!

**Comment by Qendolin** [comment]
This issue can be closed AFAICT
