### ISSUE TITLE
Crash with Canvas Renderer

### ISSUE THREAD

**Issue by emoace** [legoatoom/ConnectibleChains#2]
Hello, always wanted this feature in MC so thank you for making that a reality!

I encountered a crash when attaching a chain to a fence, I linked the crash report below.

[crash-2021-04-15_13.34.15-client.txt](https://github.com/legoatoom/ConnectibleChains/files/6320415/crash-2021-04-15_13.34.15-client.txt)

**Comment by legoatoom** [comment]
Thank you for your Issue,
A few questions.
Is this happening often, or rarely? 
Secondly, what fabric version are you using? The error comes from that my code expects a file to exist that doesn't seem to exists. This can happen when fabric's yarn is out of date, or because you are playing in 1.16.4. 

I see that you use fabric's API 0.32.0+1.16. Maybe try updating that to 0.32.5+1.16?

**Comment by legoatoom** [comment]
I realized that you cannot reopen issues if I closed them 😅
I'll keep it open for now if other people have for if other people have simmilar issues.

**Comment by legoatoom** [comment]
I found I was using a wrong library.
