### ISSUE TITLE
Missing Texture

### ISSUE THREAD

**Issue by Stanlyhalo** [legoatoom/ConnectibleChains#48]
I'm only running mods that simply do stuff like the seasonal mod, biome generation, and crop related mods. None of which are effecting this mod (even tried disabling all mods and started a new world to test). Yes, I'm running 1.19.4 fabric with the fabric api.

The issue is that it seems the first connected part will always have a missing texture:

![image](https://user-images.githubusercontent.com/36088749/236634199-6bd3b290-8ce7-49d3-8a01-227192aa4bee.png)

**Comment by Stanlyhalo** [comment]
On another note, they can't seem to go directly vertical.

**Comment by legoatoom** [comment]
I see, the problem is that you have 1 or less chains in your hand at the moment of connecting. So when it connects it removes one chain item from your hand before it tries to get the texture, thus it attempts to get the texture of air, and air does not have an item texture. So for the moment, make sure you have 2+ chains in your hand when making connections.
